classes:
- system.salt.master.pkg
- system.salt.master.api
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- system.sphinx.server.doc.reclass
- cluster.drivetrain_ha
parameters:
  _param:
    reclass_data_repository: "https://gerrit.mcp.mirantis.net/salt-models/mcp-virtual-lab"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    linux_system_codename: xenial
    salt_master_base_environment: prd
    salt_minion_ca_host: ${linux:network:fqdn}
    salt_master_host: ${_param:infra_config_deploy_address}
    salt_api_password: hovno12345!
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
  salt:
    master:
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      environment:
        prd:
          formula:
            glusterfs:
              source: pkg
              name: salt-formula-glusterfs
  linux:
    network:
      interface:
        ens4:
          enabled: true
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
  reclass:
    storage:
      class_mapping:
        common_node:
          expression: all
          node_param:
            single_address:
              value_template: <<node_control_ip>>
            linux_system_codename:
              value_template: <<node_os>>
            salt_master_host:
              value_template: <<node_master_ip>>
        infra_config:
          expression: <<node_hostname>>__startswith__cfg
          cluster_param:
            infra_config_address:
              value_template: <<node_control_ip>>
            infra_config_deploy_address:
              value_template: <<node_deploy_ip>>
            cluster_domain:
              value_template: <<node_domain>>
        cicd_control01:
          expression: <<node_hostname>>__equals__cid01
          cluster_param:
            cicd_control_node01_address:
              value_template: <<node_control_ip>>
        cicd_control02:
          expression: <<node_hostname>>__equals__cid02
          cluster_param:
            cicd_control_node02_address:
              value_template: <<node_control_ip>>
        cicd_control03:
          expression: <<node_hostname>>__equals__cid03
          cluster_param:
            cicd_control_node03_address:
              value_template: <<node_control_ip>>

