parameters:
  _param:
    cluster_domain: sl-os-ovs.local
    cluster_name: sl_os_ovs
    infra_config_deploy_address: 192.168.10.100
    infra_config_address: 172.16.10.100
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - cfg01
          - cfg01.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
