parameters:
  _param:
    cluster_domain: os_ha_contrail_40.local
    cluster_name: os_ha_contrail_40
    infra_config_deploy_address: 192.168.10.90
    infra_config_address: 172.16.10.100
    infra_config_hostname: cfg01
    linux_system_repo_mcp_salt_version: nightly
  
